export const EVENT_NAME = {
    UPDATE_PRODUCTS: "UPDATE PRODUCTS",
    ADD_ADDRESS: "ADD ADDRESS",
    PRODUCT_SELECTED: "PRODUCT SELECTED",
    PRODUCT_DETAILS: "PRODUCT DETAILS",
    MENU_CHANGED: "MENU_CHANGED"
} as const;